version: "3.4"

# Production environment override
services:
  php:
    environment:
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      SENDINBLUE_API_KEY: ${SENDINBLUE_API_KEY}
